name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Import GPG public keys
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 40976EAF437D05B5
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 3B4FE6ACC0B21F32

      - uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: "4.6.0"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12 lcov libvulkan1 libvulkan-dev vulkan-tools glslang-tools spirv-tools cmake gawk
          echo "CC=gcc-12" >> $GITHUB_ENV
          echo "CXX=g++-12" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug -- -j 2

      - name: Run unit tests
        working-directory: ${{github.workspace}}/build/test/doctests
        run: ./tester

      - name: Run code coverage
        run: |
          mkdir -p ${{github.workspace}}/coverage
          lcov --gcov-tool /usr/bin/gcov-12 --directory . --capture --output-file ${{github.workspace}}/coverage/lcov.info
          lcov --gcov-tool /usr/bin/gcov-12 --remove ${{github.workspace}}/coverage/lcov.info --output-file ${{github.workspace}}/coverage/lcov.info \
          '/usr/include/*' '/usr/lib/*' \
          '${{github.workspace}}/libs/libcsvparser/*' \
          '${{github.workspace}}/libs/libjson/*' \
          '${{github.workspace}}/libs/libsipai/src/VulkanController.cpp' \
          '${{github.workspace}}/libs/libsipai/glsl/*' \
          '${{github.workspace}}/test/*'           
          lcov --gcov-tool /usr/bin/gcov-12 --summary ${{github.workspace}}/coverage/lcov.info

      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "${{github.workspace}}/coverage/lcov.info"
          min_coverage: 80

      - name: Configure CMake for Release
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build ${{github.workspace}}/build --config Release -- -j 2

      - name: Run integration tests
        working-directory: ${{github.workspace}}/build/test/ctests
        run: ctest -C Release --output-on-failure
